# 天干地支与五行基础数据
HEAVENLY_STEMS: ["甲", "乙", "丙", "丁", "戊", "己", "庚", "辛", "壬", "癸"]
EARTHLY_BRANCHES: ["子", "丑", "寅", "卯", "辰", "巳", "午", "未", "申", "酉", "戌", "亥"]

# 五行映射关系
WUXING_MAP:
  "甲": "木"
  "乙": "木"
  "丙": "火"
  "丁": "火"
  "戊": "土"
  "己": "土"
  "庚": "金"
  "辛": "金"
  "壬": "水"
  "癸": "水"
  "寅": "木"
  "卯": "木"
  "巳": "火"
  "午": "火"
  "辰": "土"
  "戌": "土"
  "丑": "土"
  "未": "土"
  "申": "金"
  "酉": "金"
  "亥": "水"
  "子": "水"

# 五行生克关系
WUXING_RELATIONS:
  "木": { "生": "火", "克": "土", "被生": "水", "被克": "金" }
  "火": { "生": "土", "克": "金", "被生": "木", "被克": "水" }
  "土": { "生": "金", "克": "水", "被生": "火", "被克": "木" }
  "金": { "生": "水", "克": "木", "被生": "土", "被克": "火" }
  "水": { "生": "木", "克": "火", "被生": "金", "被克": "土" }

# 地支藏干映射（本气+余气）
BRANCH_HIDDEN_STEMS:
  "子": [["癸", 1.0]]
  "丑": [["己", 0.6], ["癸", 0.25], ["辛", 0.15]]
  "寅": [["甲", 0.7], ["丙", 0.2], ["戊", 0.1]]
  "卯": [["乙", 1.0]]
  "辰": [["戊", 0.6], ["乙", 0.25], ["癸", 0.15]]
  "巳": [["丙", 0.7], ["庚", 0.2], ["戊", 0.1]]
  "午": [["丁", 0.7], ["己", 0.3]]
  "未": [["己", 0.6], ["丁", 0.25], ["乙", 0.15]]
  "申": [["庚", 0.7], ["壬", 0.2], ["戊", 0.1]]
  "酉": [["辛", 1.0]]
  "戌": [["戊", 0.6], ["辛", 0.25], ["丁", 0.15]]
  "亥": [["壬", 0.7], ["甲", 0.3]]

# 十神关系映射
TEN_GODS_MAP:
  "比肩": ["甲甲", "乙乙", "丙丙", "丁丁", "戊戊", "己己", "庚庚", "辛辛", "壬壬", "癸癸"]
  "劫财": ["甲乙", "乙甲", "丙丁", "丁丙", "戊己", "己戊", "庚辛", "辛庚", "壬癸", "癸壬"]
  "食神": ["甲丙", "乙丁", "丙戊", "丁己", "戊庚", "己辛", "庚壬", "辛癸", "壬甲", "癸乙"]
  "伤官": ["甲丁", "乙丙", "丙己", "丁戊", "戊辛", "己庚", "庚癸", "辛壬", "壬乙", "癸甲"]
  "正财": ["甲己", "乙戊", "丙辛", "丁庚", "戊癸", "己壬", "庚乙", "辛甲", "壬丁", "癸丙"]
  "偏财": ["甲戊", "乙己", "丙庚", "丁辛", "戊壬", "己癸", "庚甲", "辛乙", "壬丙", "癸丁"]
  "正官": ["甲辛", "乙庚", "丙癸", "丁壬", "戊乙", "己甲", "庚丁", "辛丙", "壬己", "癸戊"]
  "七杀": ["甲庚", "乙辛", "丙壬", "丁癸", "戊甲", "己乙", "庚丙", "辛丁", "壬戊", "癸己"]
  "正印": ["甲癸", "乙壬", "丙乙", "丁甲", "戊丁", "己丙", "庚己", "辛戊", "壬辛", "癸庚"]
  "偏印": ["甲壬", "乙癸", "丙甲", "丁乙", "戊丙", "己丁", "庚戊", "辛己", "壬庚", "癸辛"]

# 生肖映射
ZODIAC_MAP:
  "子": "鼠"
  "丑": "牛"
  "寅": "虎"
  "卯": "兔"
  "辰": "龙"
  "巳": "蛇"
  "午": "马"
  "未": "羊"
  "申": "猴"
  "酉": "鸡"
  "戌": "狗"
  "亥": "猪"

# 命宫解释映射
MING_GONG_EXPLANATIONS:
  "子": "智慧深远，善于谋略，性格内敛。代表先天的智慧和思考能力。"
  "丑": "踏实稳重，耐力强，财富积累型。代表先天的稳定性和物质基础。"
  "寅": "积极进取，行动力强，领导才能。代表先天的活力和领导力。"
  "卯": "聪明敏锐，适应力强，善于交际。代表先天的适应性和社交能力。"
  "辰": "胸怀宽广，包容性强，贵人运佳。代表先天的包容性和人脉资源。"
  "巳": "思维缜密，洞察力强，适合研究。代表先天的洞察力和专注力。"
  "午": "热情开朗，精力充沛，事业心强。代表先天的热情和事业驱动力。"
  "未": "温和善良，责任心强，家庭观念重。代表先天的责任感和家庭观念。"
  "申": "机智灵活，应变力强，多才多艺。代表先天的灵活性和创造力。"
  "酉": "注重细节，完美主义，艺术天赋。代表先天的审美和艺术感知力。"
  "戌": "忠诚可靠，正义感强，适合公职。代表先天的正直和忠诚品质。"
  "亥": "感性敏锐，想象力丰富，适合创作。代表先天的直觉和想象力。"
